
export const books = [{
  book_name: "Mathematics Student Textbook",
  id: "math11",
  hashtag:["maths11","mathemathics","mathsg11"],
  book_photo: 'photo_5958448601677630277_y.jpg',
  home_dicription: "Full textbook with examples & exercises",
  type: "Textbook",
  grade_level: 11,
  curriculum: "Ethiopian Curriculum",
  prev_description: "Full textbook with examples and exercises.",
  file: "/files/grok_report.pdf",
  size: "18 MB",

}, {

  id: "phy11",
   hashtag:["phy","phusics","mathsg11"],
  book_name: "physics  Student Textbook",
  book_photo: 'photo_5958448601677630277_y.jpg',
  home_dicription: "Full textbook with examples & exercises",
  type: "Textbook",
  grade_level: 10,
  curriculum: "Ethiopian Curriculum",
  prev_description: "Complete physics textbook with problems.",
  file: "phy11.pdf",
  size: "22 MB",
},

{
  id: "bio11",
   hashtag:["bio11","biology","bio"],
  book_name: "biology Student Textbook",
  book_photo: 'photo_5958448601677630277_y.jpg',
  home_dicription: "Full textbook with examples & exercises",
  type: "Textbook",
  grade_level: 11, id: "bio11",
  curriculum: "Ethiopian Curriculum",
  prev_description: "Full textbook with examples and exercises.",
  file: "math11.pdf",
  size: "18 MB",
},
{
  id: "chem11",
   hashtag:["chem","chemistry","chemg11"],
  book_name: "chemistry Student Textbook",
  book_photo: 'photo_5958448601677630277_y.jpg',
  home_dicription: "Full textbook with examples & exercises",
  type: "Past Exam",
  grade_level: 11,
  curriculum: "Ethiopian Curriculum",
  prev_description: "Complete physics textbook with problems.",
  file: "phy11.pdf",
  size: "22 MB",
},
{
  id: "eng11",
   hashtag:["eng","english","eng11"],
  book_name: "english Student Textbook",
  book_photo: 'photo_5958448601677630277_y.jpg',
  home_dicription: "Full textbook with examples & exercises",
  type: "PDF Notes",
  grade_level: 11,
  curriculum: "Ethiopian Curriculum",
  prev_description: "Full textbook with examples and exercises.",
  file: "math11.pdf",
  size: "18 MB",
}, {
  id: "agri11",
   hashtag:["agri11","agriculter","agriculter11"],
  book_name: "agriculture Student Textbook",
  book_photo: 'photo_5958448601677630277_y.jpg',
  home_dicription: "Full textbook with examples & exercises",
  type: "PDF Notes",
  grade_level: 11,
  curriculum: "Ethiopian Curriculum",
  prev_description: "Complete physics textbook with problems.",
  file: "phy11.pdf",
  size: "22 MB",
},

{
  id: "IT11",
   hashtag:["it11","ict","itg11"],
  book_name: "IT Student Textbook",
  book_photo: 'photo_5958448601677630277_y.jpg',
  home_dicription: "Full textbook with examples & exercises",
  type: "PDF Notes",
  grade_level: 11,
  prev_description: "Full textbook with examples and exercises.",
  file: "math11.pdf",
  size: "18 MB",
},
{
  id: "biologia",
   hashtag:["bio","biology11","bio12"],
  book_name: "biology",
  book_photo: 'photo_5958448601677630277_y.jpg',
  home_dicription: "Full textbook with examples & exercises",
  type: "PDF Notes",
  curriculum: "Ethiopian Curriculum",
  prev_description: "prev_description",
  grade_level: 12,
  file: "math11.pdf",
  size: "18 MB",
},
{
id: "biologia",
   hashtag:["bio","biology11","bio12"],
  book_name: "biology",
  book_photo: 'photo_5958448601677630277_y.jpg',
  home_dicription: "Full textbook with examples & exercises",
  type: "PDF Notes",
  curriculum: "Ethiopian Curriculum",
  prev_description: "prev_description",
  grade_level: 12,
  file: "math11.pdf",
  size: "18 MB",
}
]


